# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default Coordinated Universal Time (UTC)
# file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

# sys.path pathpower allows us to import our app
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to clone for code; default is 90
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded with relative paths
# source_location = 

sqlalchemy.url = postgresql://postgres:postgrespassword@localhost:5432/fertilizer_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
